# Generated by Django 5.0.1 on 2024-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produs",
            name="pret",
            field=models.FloatField(db_index=True),
        ),
    ]
