# Generated by Django 5.0.1 on 2024-01-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_produs_descriere_alter_produs_imagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produs",
            name="descriere",
            field=models.CharField(
                blank=True,
                help_text="Introduceti o descriere",
                max_length=1024,
                null=True,
            ),
        ),
    ]
