# Generated by Django 5.0.1 on 2024-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_produs_descriere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produs",
            name="titlu",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
