# Generated by Django 5.0.1 on 2024-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
