# Generated by Django 5.0.1 on 2024-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_curs_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='an',
            field=models.IntegerField(default=1),
        ),
    ]
