# Generated by Django 5.0.1 on 2024-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='elev',
            name='prenume',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='elev',
            unique_together={('nume', 'prenume')},
        ),
    ]
