# Generated by Django 5.0.1 on 2024-02-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_produs_created_produs_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrebare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_intrebare', models.CharField(max_length=10)),
                ('text_raspuns', models.CharField(max_length=100)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produs')),
            ],
        ),
    ]
