# Generated by Django 5.0.1 on 2024-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_recenzie_descriere_alter_recenzie_titlu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrebare',
            name='text_intrebare',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intrebare',
            name='text_raspuns',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recenzie',
            name='titlu',
            field=models.CharField(max_length=10),
        ),
    ]
