# Generated by Django 5.0.1 on 2024-02-20 17:34

from django.db import migrations


def forward(apps, models):
    print("\nInainte")
    Produs = apps.get_model('app', 'Produs')
    Produs.objects.update(stoc=100)


def backward(apps, models):
    raise Exception("Cannot go back")
    print("\nInapoi")

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_produs_stoc'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
