# Generated by Django 5.0.1 on 2024-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_datamigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prenume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
