# Generated by Django 5.0.1 on 2024-02-20 17:45

from django.db import migrations

def forward(apps, models):
    Student = apps.get_model('app', 'Student')
    for student in Student.objects.all():
        try:
            prenume, nume = student.nume.split(" ")
            student.prenume = prenume
            student.nume = nume
            student.save()
        except ValueError:
            print(f"Nu am putut migra userul {student.pk}")


def backward(apps, models):
    Student = apps.get_model('app', 'Student')
    for student in Student.objects.all():
        try:
            student.nume = " ".join((student.prenume, student.nume))
            student.prenume = None
            student.save()
        except (TypeError, ValueError):
            print(f"Nu am putut migra userul {student.pk}")
    

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_student_prenume'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
